pid: tmp/pids/thin.pid
address: 0.0.0.0
timeout: 30
wait: 30
port: 7000
log: log/thin.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
servers: 3
daemonize: true
chdir: /var/www/lensesly/current
